#!/usr/bin/env python3
"""
Figure 1B - Nanopore (NanoCount) Cortex TRP gene expression (TPM)

Reads TRP gene-level TPMs (with replicate columns) and generates a
publication-ready bar plot of mean TPM per TRP gene, coloured by TRP family.

Inputs:
  - TRP_TPM_CortexMean_NanoCount.tsv (generated by downstream/tpm/00_tables/00_nanocount_gene_TPM_cortex.py)

Outputs:
  - TRP_TPM_CortexMean_NanoCount_panel.pdf
  - TRP_TPM_CortexMean_NanoCount_ordered.tsv

Notes:
  - Designed for Ensembl r115 TRP gene set order (TRPML/TRPP/TRPA/TRPC/TRPM/TRPV).
  - Uses Arial if available; otherwise falls back to DejaVu Sans.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
import seaborn as sns


# ------------------------- helpers -------------------------


def get_family(gene: str) -> str:
    n = str(gene).lower()
    if n.startswith("trpc"):
        return "TRPC"
    if n.startswith("trpv"):
        return "TRPV"
    if n.startswith("trpm"):
        return "TRPM"
    if n.startswith("trpa"):
        return "TRPA"
    if n.startswith("pkd"):
        return "TRPP"
    if n.startswith("mcoln"):
        return "TRPML"
    return "Other"


def nice_case(gene: str) -> str:
    s = str(gene).lower()
    if s.startswith("trp") and len(s) >= 4:
        return s[:4].capitalize() + s[4:]
    if s.startswith("pkd"):
        return "Pkd" + s[3:]
    if s.startswith("mcoln"):
        return "Mcoln" + s[5:]
    return s.capitalize()


def pick_font() -> str:
    available = {f.name for f in fm.fontManager.ttflist}
    return "Arial" if "Arial" in available else "DejaVu Sans"


# ------------------------- main -------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot Fig 1B: Nanopore (NanoCount) Cortex TRP mean TPM bar plot."
    )
    parser.add_argument(
        "--infile",
        type=Path,
        required=True,
        help="Input TSV (TRP_TPM_CortexMean_NanoCount.tsv).",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        required=True,
        help="Output directory for PDF + ordered TSV.",
    )
    parser.add_argument(
        "--ytick-step",
        type=float,
        default=10.0,
        help="Y-axis tick step (default: 10).",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=600,
        help="Export DPI for PDF (default: 600).",
    )
    args = parser.parse_args()

    infile: Path = args.infile
    outdir: Path = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    out_pdf = outdir / "TRP_TPM_CortexMean_NanoCount_panel.pdf"
    out_tsv = outdir / "TRP_TPM_CortexMean_NanoCount_ordered.tsv"

    font_choice = pick_font()

    plt.rcParams.update(
        {
            "font.family": font_choice,
            "font.size": 14,
            "axes.labelsize": 18,
            "xtick.labelsize": 12,
            "ytick.labelsize": 14,
            "legend.fontsize": 12,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "text.color": "black",
            "axes.labelcolor": "black",
            "xtick.color": "black",
            "ytick.color": "black",
            "axes.edgecolor": "black",
        }
    )
    sns.set_style("white")

    trp = pd.read_csv(infile, sep="\t")

    # Accept either "Gene" or "gene_name" column
    if "Gene" in trp.columns:
        trp["GeneName"] = trp["Gene"].astype(str)
    elif "gene_name" in trp.columns:
        trp["GeneName"] = trp["gene_name"].astype(str)
    else:
        raise ValueError("Input TSV must contain either 'Gene' or 'gene_name' column.")

    # Ensure expected numeric columns exist (robust to missing fields)
    for c in ["TPM_rep1", "TPM_rep2", "TPM_rep3", "TPM_mean"]:
        if c not in trp.columns:
            trp[c] = 0.0
        trp[c] = pd.to_numeric(trp[c], errors="coerce").fillna(0.0)

    # Canonical TRP gene plotting order
    gene_order = [
        "mcoln1",
        "mcoln2",
        "mcoln3",
        "pkd2",
        "pkd2l1",
        "pkd2l2",
        "trpa1",
        "trpc1",
        "trpc2",
        "trpc3",
        "trpc4",
        "trpc5",
        "trpc6",
        "trpc7",
        "trpm1",
        "trpm2",
        "trpm3",
        "trpm4",
        "trpm5",
        "trpm6",
        "trpm7",
        "trpm8",
        "trpv1",
        "trpv2",
        "trpv3",
        "trpv4",
        "trpv5",
        "trpv6",
    ]

    want = pd.DataFrame(
        {
            "GeneName": [nice_case(g) for g in gene_order],
            "_key": [g.upper() for g in gene_order],
        }
    )

    trp["family"] = trp["GeneName"].apply(get_family)
    have = trp.copy()
    have["_key"] = have["GeneName"].str.upper()

    merged = want.merge(
        have[["GeneName", "family", "TPM_rep1", "TPM_rep2", "TPM_rep3", "TPM_mean", "_key"]],
        on="_key",
        how="left",
    )

    for c in ["TPM_rep1", "TPM_rep2", "TPM_rep3", "TPM_mean"]:
        merged[c] = merged[c].fillna(0.0)

    merged["family"] = merged["family"].fillna(merged["GeneName"].map(get_family))
    merged = merged[merged["family"] != "Other"].copy()

    ordered_labels = [nice_case(g) for g in gene_order]
    merged["label"] = pd.Categorical(merged["GeneName"], categories=ordered_labels, ordered=True)
    merged = merged.sort_values("label", kind="stable")

    # Save ordered data used for plotting
    merged.loc[:, ["GeneName", "family", "TPM_rep1", "TPM_rep2", "TPM_rep3", "TPM_mean"]].to_csv(
        out_tsv, sep="\t", index=False
    )

    palette = {
        "TRPML": "#4682b4",
        "TRPP": "#dda0dd",
        "TRPA": "#696969",
        "TRPC": "#fc8d62",
        "TRPM": "#66a61e",
        "TRPV": "#8da0cb",
    }
    hue_order = ["TRPML", "TRPP", "TRPA", "TRPC", "TRPM", "TRPV"]

    d = merged.copy()
    max_val = float(d["TPM_mean"].max()) if len(d) else 0.0
    step = float(args.ytick_step)
    top = float(np.ceil(max_val / step) * step) if max_val > 0 else step
    yticks = np.arange(0, top + step, step)

    # Layout: main axis + separate legend axis (Nature-style)
    fig = plt.figure(figsize=(8.5, 4.5))
    gs = fig.add_gridspec(1, 2, width_ratios=[7.2, 1.2], wspace=0.05)
    ax = fig.add_subplot(gs[0, 0])
    ax_leg = fig.add_subplot(gs[0, 1])
    ax_leg.axis("off")

    sns.barplot(
        x="label",
        y="TPM_mean",
        hue="family",
        data=d,
        dodge=False,
        palette=palette,
        hue_order=hue_order,
        ax=ax,
    )

    ax.margins(x=0.01)
    ax.set_xlabel("Gene", labelpad=6)
    ax.set_ylabel("TPM (Cortex)", labelpad=10)

    ax.set_yticks(yticks)
    ax.set_ylim(0, top)
    ax.margins(y=0.02)

    ax.yaxis.grid(True, linestyle=":", linewidth=0.7, color="lightgrey")
    ax.set_axisbelow(True)

    for spine in ["left", "bottom"]:
        ax.spines[spine].set_linewidth(1.2)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

    ax.tick_params(
        axis="both",
        which="both",
        direction="out",
        length=3.8,
        width=1.0,
        color="black",
        bottom=True,
        top=False,
        left=True,
        right=False,
    )
    ax.tick_params(axis="x", pad=2)
    plt.setp(ax.get_xticklabels(), rotation=60, ha="right")

    handles, labels = ax.get_legend_handles_labels()
    if ax.get_legend() is not None:
        ax.get_legend().remove()

    ax_leg.legend(
        handles,
        labels,
        title="Gene family",
        loc="center left",
        frameon=False,
        borderaxespad=0.0,
        title_fontsize=14,
        fontsize=12,
    )

    fig.subplots_adjust(bottom=0.32, left=0.12, right=0.98, top=0.90)
    fig.savefig(out_pdf, dpi=args.dpi, format="pdf", bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_tsv}")


if __name__ == "__main__":
    main()

