#!/usr/bin/env python3
"""
Supplementary Fig. S1a — Nanopore (NanoCount) Cortex TRP gene read counts

Reads TRP gene-level read counts (with replicate columns) and generates a
publication-ready bar plot of mean read count per TRP gene, coloured by TRP family.

Inputs:
  - TRP_ReadCounts_cortex_reps_with_mean_FROM_NanoCount.tsv
    (generated by downstream/tpm/00_tables/01_nanocount_gene_counts_cortex.py)

Outputs:
  - TRP_ReadCounts_CortexMean_NanoCount_panel.pdf
  - TRP_ReadCounts_CortexMean_NanoCount_ordered.tsv

Notes:
  - Uses Arial if available; otherwise falls back to DejaVu Sans.
  - Automatically chooses a “nice” y-tick step based on the max count.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
import seaborn as sns


# ------------------------- helpers -------------------------


def get_family(gene: str) -> str:
    n = str(gene).lower()
    if n.startswith("trpc"):
        return "TRPC"
    if n.startswith("trpv"):
        return "TRPV"
    if n.startswith("trpm"):
        return "TRPM"
    if n.startswith("trpa"):
        return "TRPA"
    if n.startswith("pkd"):
        return "TRPP"
    if n.startswith("mcoln"):
        return "TRPML"
    return "Other"


def nice_case(gene: str) -> str:
    s = str(gene).lower()
    if s.startswith("trp") and len(s) >= 4:
        return s[:4].capitalize() + s[4:]
    if s.startswith("pkd"):
        return "Pkd" + s[3:]
    if s.startswith("mcoln"):
        return "Mcoln" + s[5:]
    return s.capitalize()


def pick_font() -> str:
    available = {f.name for f in fm.fontManager.ttflist}
    return "Arial" if "Arial" in available else "DejaVu Sans"


def nice_step(x: float) -> int:
    if x <= 500:
        return 50
    if x <= 2000:
        return 200
    if x <= 5000:
        return 500
    if x <= 20000:
        return 2000
    if x <= 50000:
        return 5000
    return 10000


# ------------------------- main -------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot Supp Fig S1a: Nanopore (NanoCount) Cortex TRP mean read counts."
    )
    parser.add_argument(
        "--infile",
        type=Path,
        required=True,
        help="Input TSV (TRP_ReadCounts_cortex_reps_with_mean_FROM_NanoCount.tsv).",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        required=True,
        help="Output directory for PDF + ordered TSV.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=600,
        help="Export DPI for PDF (default: 600).",
    )
    parser.add_argument(
        "--annotate",
        action="store_true",
        help="If set, annotate bars with count labels (default: off).",
    )
    args = parser.parse_args()

    infile: Path = args.infile
    outdir: Path = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    out_pdf = outdir / "TRP_ReadCounts_CortexMean_NanoCount_panel.pdf"
    out_tsv = outdir / "TRP_ReadCounts_CortexMean_NanoCount_ordered.tsv"

    font_choice = pick_font()

    plt.rcParams.update(
        {
            "font.family": font_choice,
            "font.size": 14,
            "axes.labelsize": 18,
            "xtick.labelsize": 12,
            "ytick.labelsize": 14,
            "legend.fontsize": 12,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "text.color": "black",
            "axes.labelcolor": "black",
            "xtick.color": "black",
            "ytick.color": "black",
            "axes.edgecolor": "black",
        }
    )
    sns.set_style("white")

    trp = pd.read_csv(infile, sep="\t")

    # Accept either "Gene" or "gene_name" column
    if "Gene" in trp.columns:
        trp["GeneName"] = trp["Gene"].astype(str)
    elif "gene_name" in trp.columns:
        trp["GeneName"] = trp["gene_name"].astype(str)
    else:
        raise ValueError("Input TSV must contain either 'Gene' or 'gene_name' column.")

    if "Counts_mean" not in trp.columns:
        raise ValueError("Counts_mean column not found in input TSV.")

    # Coerce all Counts_* columns to numeric
    for c in [c for c in trp.columns if c.lower().startswith("counts")]:
        trp[c] = pd.to_numeric(trp[c], errors="coerce").fillna(0.0)

    # Canonical TRP gene plotting order
    gene_order = [
        "mcoln1",
        "mcoln2",
        "mcoln3",
        "pkd2",
        "pkd2l1",
        "pkd2l2",
        "trpa1",
        "trpc1",
        "trpc2",
        "trpc3",
        "trpc4",
        "trpc5",
        "trpc6",
        "trpc7",
        "trpm1",
        "trpm2",
        "trpm3",
        "trpm4",
        "trpm5",
        "trpm6",
        "trpm7",
        "trpm8",
        "trpv1",
        "trpv2",
        "trpv3",
        "trpv4",
        "trpv5",
        "trpv6",
    ]

    want = pd.DataFrame(
        {"GeneName": [nice_case(g) for g in gene_order], "_key": [g.upper() for g in gene_order]}
    )

    trp["family"] = trp["GeneName"].apply(get_family)
    trp["_key"] = trp["GeneName"].str.upper()

    merged = want.merge(trp, on="_key", how="left", suffixes=("", "_have"))
    merged["GeneName"] = merged["GeneName"].fillna(merged.get("GeneName_have"))
    merged["family"] = merged["family"].fillna(merged["GeneName"].map(get_family))

    # Fill missing numeric values with 0
    for c in [c for c in merged.columns if c.lower().startswith("counts")]:
        merged[c] = pd.to_numeric(merged[c], errors="coerce").fillna(0.0)

    merged = merged[merged["family"] != "Other"].copy()

    ordered_labels = [nice_case(g) for g in gene_order]
    merged["label"] = pd.Categorical(merged["GeneName"], categories=ordered_labels, ordered=True)
    merged = merged.sort_values("label", kind="stable")

    # Save ordered data used for plotting
    save_cols = ["GeneName", "family"] + [
        c for c in ["Counts_rep1", "Counts_rep2", "Counts_rep3", "Counts_mean"] if c in merged.columns
    ]
    merged.loc[:, save_cols].to_csv(out_tsv, sep="\t", index=False)

    palette = {
        "TRPML": "#4682b4",
        "TRPP": "#dda0dd",
        "TRPA": "#696969",
        "TRPC": "#fc8d62",
        "TRPM": "#66a61e",
        "TRPV": "#8da0cb",
    }
    hue_order = ["TRPML", "TRPP", "TRPA", "TRPC", "TRPM", "TRPV"]

    d = merged.copy()
    max_val = float(d["Counts_mean"].max()) if len(d) else 0.0
    step = nice_step(max_val) if max_val > 0 else 50
    top = float(np.ceil(max_val / step) * step) if max_val > 0 else float(step)
    yticks = np.arange(0, top + step, step)

    # Layout: main axis + separate legend axis (Nature-style)
    fig = plt.figure(figsize=(8.5, 4.5))
    gs = fig.add_gridspec(1, 2, width_ratios=[7.2, 1.2], wspace=0.05)
    ax = fig.add_subplot(gs[0, 0])
    ax_leg = fig.add_subplot(gs[0, 1])
    ax_leg.axis("off")

    sns.barplot(
        x="label",
        y="Counts_mean",
        hue="family",
        data=d,
        dodge=False,
        palette=palette,
        hue_order=hue_order,
        ax=ax,
    )

    ax.margins(x=0.01)
    ax.set_xlabel("Gene", labelpad=6)
    ax.set_ylabel("Read count (Cortex)", labelpad=10)

    ax.set_yticks(yticks)
    ax.set_ylim(0, top)
    ax.margins(y=0.02)

    ax.yaxis.grid(True, linestyle=":", linewidth=0.7, color="lightgrey")
    ax.set_axisbelow(True)

    for spine in ["left", "bottom"]:
        ax.spines[spine].set_linewidth(1.2)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

    ax.tick_params(
        axis="both",
        which="both",
        direction="out",
        length=3.8,
        width=1.0,
        color="black",
        bottom=True,
        top=False,
        left=True,
        right=False,
    )
    ax.tick_params(axis="x", pad=2)
    plt.setp(ax.get_xticklabels(), rotation=60, ha="right")

    handles, labels = ax.get_legend_handles_labels()
    if ax.get_legend() is not None:
        ax.get_legend().remove()

    ax_leg.legend(
        handles,
        labels,
        title="Gene family",
        loc="center left",
        frameon=False,
        borderaxespad=0.0,
        title_fontsize=14,
        fontsize=12,
    )

    if args.annotate:
        for p in ax.patches:
            h = p.get_height()
            r = int(round(h))
            if r == 0:
                continue
            ax.annotate(
                f"{r:,}",
                (p.get_x() + p.get_width() / 2.0, h),
                ha="center",
                va="bottom",
                fontsize=8,
                color="black",
                xytext=(0, 4),
                textcoords="offset points",
                clip_on=False,
            )

    fig.subplots_adjust(bottom=0.32, left=0.12, right=0.98, top=0.90)
    fig.savefig(out_pdf, dpi=args.dpi, format="pdf", bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_tsv}")


if __name__ == "__main__":
    main()

